### ISSUE TITLE
Design and Planning

### ISSUE THREAD

**Issue by ydh1304** [ydh1304/SUB-web#1]
- [x] Relation schema diagram
- [x] View 동욱
- [x] Controller 동현
- [x] Design Details 규석
- [x] Frontend Algorithms 동현
- [x] Frontent Relations 동욱
- [x] Backend Design 규석
- [x] Implementation plan
- [x] Testing Plan

**Comment by ydh1304** [comment]
View | Controller 			(view → model, model 			→ view) | Model
-- | -- | --
Sign 			up | /signup/ 			username, 			password, email, nickname | User
Log 			in | /api-token-auth/ 			username, 			password | User
Main | / 			content 			type ,query 			/ 			content 			list | Sale 			Purchase
Create 			contents | /sale, 			/purchase 			content 			object, book object | Sale 			Purchase 			Book
My 			page | /user/ 			user 			object 			/mypage/ 			user 			object | User
Content 			details | /sale/:id, 			/purchase/:id 			content 			object | Sale 			Purchase
Content 			details | /comment/ 			comment 			object, saleId or purchaseId 			/sale/:id, 			/purchase/:id 			comment 			object | Comment

**Comment by ydh1304** [comment]
![image](https://user-images.githubusercontent.com/29620640/39420500-c01e2ac6-4c9f-11e8-8591-28914fbd8b90.png)

**Comment by ydh1304** [comment]
![image](https://user-images.githubusercontent.com/29620640/39423350-810cfb02-4cac-11e8-8161-68ac4ab2bf7f.png)

**Comment by yks1502** [comment]
[소개원실.zip](https://github.com/ydh1304/SUB-web/files/1960210/default.zip)

**Comment by ydh1304** [comment]
Unit Testing
we would test every implemented modules by following frameworks.
- React: jest & Enzyme
- Django: Python unit test

Functional Testing
we would test create, authentication, search books and contents.
- React: jest & Enzyme
- Django: Python unit test

Acceptance & Integration Testing
We would evaluate our acceptance and integration by ourselves.
